# Generated by Django 2.2.7 on 2019-11-18 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_ui', '0002_remove_post_header_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'published', 'ordering': ('-published',), 'permissions': [('no_moderation_required', 'Can post without premoderation')], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
